Quiz listing
muskanbagrecha/quiz-react-app pull request #2
Opened 2022-04-18 19:36 UTC by muskanbagrecha

Please review PR for the quiz listing page and dark theme

- Db will be updated in the next PR. For now, you can check the first category (TV shows) to get a look and feel.
- On selecting a category, the user will be redirected to the quiz listing page (for that category).
- The explore button on the hero will redirect the user to the quiz listing page with all the quizzes. 
- Files to review:

2022-04-18 21:49 UTC, zoef-yt requested changes

2022-04-18 21:49 UTC, zoef-yt commented on README.md
>  ```
Do change readme according to your project.

2022-04-18 21:49 UTC, zoef-yt commented on public/index.html
> +<html lang="en" data-theme="light">
Appreciation: Both the theme overall looks really great loved the color combination nice work.

2022-04-18 21:49 UTC, zoef-yt commented on src/pages/quizListingPage/QuizListingPage.css
> +    /* height: 12rem; */
Remove commented code.

2022-04-18 21:49 UTC, zoef-yt commented on src/pages/quizListingPage/QuizListingPage.jsx
> +      <h1 className="styled-title">Featured Quizzes</h1>
If I am not wrong this should be just "Quizzes" and not "Featured Quizzes".
Also on this page, I can come from the home page where I can select any category to see the following category quizzes on this page but there is no way to change the category on this page and there is also no indication on this page which category is selected so make sure to look into this.

2022-04-18 21:49 UTC, zoef-yt commented on src/pages/quizListingPage/QuizListingPage.jsx
> +                  <button
![image](https://user-images.githubusercontent.com/67889207/163881766-cba4e97e-a87b-4e6f-9ad5-ac1833fd7cdb.png)
UI-Suggestion: on hover make the box shadow a little less.

2022-04-18 21:49 UTC, zoef-yt commented on src/components/UI/navigation/Navigation.jsx
> +        {/* <li>
Remove commented code.

2022-04-18 21:49 UTC, zoef-yt commented on src/index.css
> +    --color-white: rgb(247, 247, 247);
This is repeated can be removed.

2022-04-18 21:49 UTC, zoef-yt commented on src/index.css
> +    --card-shadow: 0 3px 6px rgba(0,0,0,0.16), 0 3px 6px rgba(0,0,0,0.23);
This repeated can be removed.

2022-04-18 21:49 UTC, zoef-yt commented on src/router/AppRouter.jsx
> +import { Homepage, RulesPage, PageNotFound, QuizListingPage } from "../pages";
UI Suggestion on Hompage.
![image](https://user-images.githubusercontent.com/67889207/163882919-9b506a53-63ba-4ee6-b641-575fcc39f0c5.png)
Because of the background image the text "technology" blends with the background which makes it harder to read also add the hover effect  on these buttons which you have added to the above button(hero banner explore button).

2022-04-19 11:01 UTC, bhtibrewal approved these changes
I couldn't find any mistakes, you are good to merge

2022-04-19 13:23 UTC, muskanbagrecha commented on src/pages/quizListingPage/QuizListingPage.jsx
> +      <h1 className="styled-title">Featured Quizzes</h1>
Makes sense, thank you.

2022-04-19 13:27 UTC, muskanbagrecha commented
@zoef-yt done with all the changes in PR #3.

2022-04-19 14:39 UTC, zoef-yt approved these changes
As you have done with all the changes you can merge this branch. Really great work with the UI. Love how both your theme looks. Great work Muskan. Good to merge.

2022-04-19 15:18 UTC, pankaj-prog approved these changes
Overall work is great.

2022-04-19 15:18 UTC, pankaj-prog commented on src/index.css
>      height: 100vh;
this should be: min-height as 100vh, you couldn't see any problem in the UI because the content is overflowing.

2022-05-02 09:43 UTC, merged